
const errors = {
    "204": "NO_CONTENT",
    "304": "NOT_MODIFIED",
    "400": "BAD_REQUEST",
    "401": "UNAUTHORIZED",
    "403": "FORBIDDEN_REQUEST",
    "404": "NOT_FOUND",
    "405": "METHOD_NOT_ALLOWED",
    "406": "NOT_ACCEPTABLE",
    "407": "PROXY_AUTHENTICATION_REQUIRED",
    "408": "REQUEST_TIMEOUT",
    "409": "CONFLICT",
    "415": "UNSUPPORTED_MEDIA_TYPE",
    "500": "INTERNAL_SERVER_ERROR",
    "600": "GENERIC_ERROR_CODE",
    "P001": "PRICE_SHEET_UNSAVED",
    "P002": "ROUTE_NOT_FOUND",
    "P003": "NO_POLICY_APPLIED",
    "NOTIFICATION_ERROR": "NOTIFICATION_ERROR",
    "PRODUCER_ERROR": "PRODUCER_ERROR"
};

export default errors;
